# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('body', models.CharField(max_length=255)),
                ('favorite_teacher', models.CharField(max_length=64)),
                ('approved', models.NullBooleanField(default=None)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
